POST http://localhost:5050/users/create HTTP/1.1
Content-Type: application/json

{
    "name":"Gabriele",
    "username":"Admin!",
    "email": "nasone@gmail.com",
    "password": "Lamiapassword",
    "role": "admin"
}

####
GET http://localhost:5050/users
####
GET http://localhost:5050/users/6547d6fa9224829eb7385c40

####
PATCH http://localhost:5050/users/update/6547d6fa9224829eb7385c40 HTTP/1.1
Content-Type: application/json

{
    "role":"admin"
}

####
DELETE  http://localhost:5050/users/delete/653b6a2b64f3807f4d7689d7 

####
GET http://localhost:5050/travels

####
GET http://localhost:5050/travels/category/Relax

####
GET http://localhost:5050/travels/653bfbef63c23350e5cec733

####
POST http://localhost:5050/travels/create HTTP/1.1
Content-Type: application/json

{
    "category": "Learnings and Tips",
    "title": "Le ultime uscite",
    "content": "WOWOWOWOW",
    "price": 699
}

####
PATCH http://localhost:5050/travels/update/653bfbef63c23350e5cec733
Content-Type: application/json

{
    "cover":"https://striveschool.ghost.io/content/images/2020/11/tips02.png",
    "content":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
}

####
DELETE http://localhost:5050/travels/delete/653bfbef63c23350e5cec733

####
GET http://localhost:5050/travels/653bfbef63c23350e5cec733/testimonials

####
POST http://localhost:5050/travels/653bfbef63c23350e5cec733 HTTP/1.1
Content-Type: application/json

{
    "testimonial": "Incredibileeeeeee",
    "valutation":"10"
}

####
GET http://localhost:5050/travels/653bfbef63c23350e5cec733/testimonials/653e2f55fa92348261d8ab0f

####
PUT http://localhost:5050/travels/653bfbef63c23350e5cec733/testimonials/653e2f55fa92348261d8ab0f
Content-Type: application/json

{
    "testimonial": "Prova modifica",
    "valutation" : "5"
}

####
DELETE http://localhost:5050/travels/653bfbef63c23350e5cec733/testimonials/653e2f55fa92348261d8ab0f